---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: devops
spec:
 replicas: 3
 selector:
  matchLabels:
   app: devops
 template:
  metadata:
   labels:
    app: devops
  spec:
   containers:
    - name: devops
      image: gcr.io/vaulted-quarter-260801/devops:tagversion
      ports:
      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: devops
spec:
  type: LoadBalancer 
  selector:
   app: devops
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
